const fs = require('fs');
const fileName = 'example.txt';
const dataToWrite = 'This is a sample text written using Node.js file handling.\n';
fs.writeFileSync(fileName, dataToWrite);
console.log('File created and data written.');
let readData = fs.readFileSync(fileName, 'utf8');
console.log('Data read from file:');
console.log(readData);
const moreData = 'Appending more content to the file.\n';
fs.appendFileSync(fileName, moreData);
console.log('Data appended successfully.');
readData = fs.readFileSync(fileName, 'utf8');
console.log('Updated file content:');
console.log(readData);
const newFileName = 'renamed_example.txt';
fs.renameSync(fileName, newFileName);
console.log('File renamed successfully.');
const copyFileName = 'copy_example.txt';
fs.copyFileSync(newFileName, copyFileName);
console.log('File copied successfully.');
fs.unlinkSync(copyFileName);
console.log('Copied file deleted successfully.');
